# Generated by Django 4.1.7 on 2023-04-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choice_userchoice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserChoice',
            new_name='Choice',
        ),
    ]
