# Generated by Django 4.1.7 on 2023-05-14 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_profile_orderentry_order_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shopping_cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shop.order'),
        ),
    ]
