# Generated by Django 4.1.7 on 2023-05-16 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderentry',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_entries', to='shop.order'),
            preserve_default=False,
        ),
    ]
